README.rst, sphinx_autobuild/__init__.py, sphinx_autobuild/test/test_autobuild.py
Based on the feature/1-arbitrary-watch branch.
I have rebased, documented, fixed, and tested the feature. I also comprehensively tested the rest of the optional arguments.
Tested both py.test and travis.cl.
=> Arbitrary watch -- allow user to manually watch dirs

sphinx_autobuild/__init__.py, sphinx_autobuild/test/test_autobuild.py, sphinx_autobuild/test/test_ignored.py
Fixes #24 by providing an additional argument `-r` to pass in a regular expression to ignore paths.
=> Support ignoring files using regular expressions

README.rst, requirements.txt, sphinx_autobuild/__init__.py
When working with multiple Sphinx document repositories at one time (e.g., when working with related documents that have cross-referencing intersphinx links), I often need to have multiple browser windows active with multiple sphinx-autobuild processes running. It became tedious and difficult to manually give them all unique port numbers and to start browser windows. These two changes allow a script that includes lines like those below to automatically open browser windows for every Sphinx document I am working on as I run sphinx-autobuild.
Sorry that I didn't include documentation changes and tests. I just don't have the time (but the changes are very minor, with a good bang-for-the-buck value, so I wanted to at least contribute them for consideration). 
make clean 2>/dev/null
(sleep 1 …
=> Add capability to select random port and automatically start browser at URL

sphinx_autobuild/__init__.py
This PR is intended to fix compatibility with livereload version >= 2.4.1
This version of livereload changed the API for watchers. It now expected a keyword parameter called `ignore`.
Fix #39 
Fix #40
=> Added support for livereload >=2.4.1

README.rst
`--poll` needs documentation. My path to discovering it was by reading closed issues and viewing the source code for the commit that adds it.
=> Add --poll to README

sphinx_autobuild/__init__.py
Simply prints **version** and exits
=> Add -v version argument

pyproject.toml, src/sphinx_autobuild/sphinx.py
Fixes #58
Fixes #74 
Some of my CI/CD pipelines were failing because of this. The problem arises if `sphinx-build` in the local PATH points to a different python version from the main `sys.executable`.
=> Don't depend on sphinx-build on PATH, use sphinx installed on the same interpreter

pyproject.toml
I'm assuming the project/repository was transferred here, but the link that is still published on pypi.org returns a 404.
=> [DOC] Correct link to project on pypi

README.md
https://www.pokemon.com/us/pokedex/magikarp
=> Fix typo in pokemon name

src/sphinx_autobuild/cli.py
For the longest time I've wondered why sphinx-autobuild would get stuck
in an infinite rebuild loop, even though I'd ignored the directories I
needed too. Turns out, --ignore only worked with absolute paths, which
seems like an odd thing to work for anyone.
This allows either relative or absolute paths, and passes globs through
unharmed.
=> ENH: Allow passing relative paths to --ignore

pyproject.toml
Add the Sphinx PyPi classifier so that the package shows up in the correct [PyPi filters](https://pypi.org/search/?c=Framework+%3A%3A+Sphinx).
=> Add Sphinx PyPi classifier

CONTRIBUTING.md, README.md
It appears that the underlying issue in sphinx causing #34 (live reloading not working for autodoc'd code files and other static files) is at partially fixed. I get automatic rebuilds and browser reloads when I update my code files (as long as the directory they're in is watched). Still no reloads for other static files, but the code files were the biggest pain point since that's where most of the docs live for many of us using autodoc.
This PR updates the README "sphinx bugs" section accordingly. I also fixed a dead link to the EBP contributing guide.
=> Docs update to reflect sphinx progress on #34

README.md, src/sphinx_autobuild/build.py
Adds support for passing `sphinx-build`'s `--color` option to `sphinx-autobuild` and updates the docs for that and #109
=> Add support for passing `--color` option

src/sphinx_autobuild/cli.py
#109 added `--keep-going` option but when used the `getattr` function call in `cli.py` was creating this error callback :
```console
Traceback (most recent call last):
File ".venv/bin/sphinx-autobuild", line 8, in <module>
sys.exit(main())
File "/workspaces/comboard-linux-image/docs/.venv/src/sphinx-autobuild/src/sphinx_autobuild/cli.py", line 176, in main
build_args, pre_build_commands = _get_build_args(args)
File "/workspaces/comboard-linux-image/docs/.venv/src/sphinx-autobuild/src/sphinx_autobuild/cli.py", line 21, in _get_build_args
val = getattr(args, arg)
AttributeError: 'Namespace' object has no attribute '-keep-going'
```
This MR fixes that bug by converting the args namespace to a dictonnary and using arg_dict.get instead.
I'm not sure how clean is this solution since it's no …
=> fix '--keep-going' sphinx argument error

pyproject.toml
The watchfiles dependency used in `server.py` is missing from requirements.
Since the changes 5 days ago, with a clean install, you get the following error:
```
$ sphinx-autobuild
Traceback (most recent call last):
File "/.../sphinx-autobuild", line 5, in <module>
from sphinx_autobuild.__main__ import main
File "/.../sphinx_autobuild/__main__.py", line 22, in <module>
from sphinx_autobuild.server import RebuildServer
File "/.../sphinx_autobuild/server.py", line 8, in <module>
import watchfiles
ModuleNotFoundError: No module named 'watchfiles'
```
After installing `watchfiles` the project runs successfully. This PR adds the package as a dependency in `pyproject.toml`.
=> Add watchfiles as dependency

.pre-commit-config.yaml, pyproject.toml
With the new sphinx-autobuild 2024.4.13, I'm getting `ModuleNotFoundError: No module named 'watchfiles'` with https://github.com/python/peps/:
```pytb
❯ make clean venv htmllive
rm -rf .venv
rm -rf build topic
Creating venv in .venv
Requirement already satisfied: pip in ./.venv/lib/python3.12/site-packages (24.0)
Collecting wheel
Using cached wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
Using cached wheel-0.43.0-py3-none-any.whl (65 kB)
Installing collected packages: wheel
Successfully installed wheel-0.43.0
Collecting Pygments>=2.9.0 (from -r requirements.txt (line 2))
Using cached pygments-2.17.2-py3-none-any.whl.metadata (2.6 kB)
Collecting Sphinx!=6.1.0,!=6.1.1,>=5.1.1 (from -r requirements.txt (line 5))
Using cached sphinx-7.2.6-py3-none-any.whl.metadata (5.9 kB)
Collecting …
```
=> Format and validate pyproject.toml

pyproject.toml, sphinx_autobuild/__main__.py, tests/test_application.py
This should catch obvious errors of the form of #155.
A
=> Add a basic integration test

.pre-commit-config.yaml, pyproject.toml
Running regular update `pre-commit autoupdate`...
Moreover curious if it would be possible to install this [bot](https://github.com/marketplace/pre-commit-ci), which would help with fixing open PRs and do these regular updates automatically (via PR so all is validated before merge)
```yaml
ci:
autofix_prs: true
autoupdate_commit_msg: "[pre-commit.ci] pre-commit suggestions"
autoupdate_schedule: quarterly
```
cc: @AA-Turner @hugovk
=> Update pre-commit hook versions

sphinx_autobuild/__main__.py, sphinx_autobuild/build.py
See commit messages for more details
=> fix #148 and #162

sphinx_autobuild/__main__.py
Fixes https://github.com/sphinx-doc/sphinx-autobuild/issues/177.
With sphinx-autobuild 2023.9.3 and the https://github.com/python/peps repo:
```pytb
❯ make clean
rm -rf .venv
rm -rf build topic
❯ sphinx-autobuild --builder html --jobs auto  --re-ignore="/\.idea/|/venv/|/pep-0000.rst|/topic/" --open-browser --delay 0 --port 55302 peps build
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.13/bin/sphinx-autobuild", line 8, in <module>
sys.exit(main())
~~~~^^
File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sphinx_autobuild/__main__.py", line 34, in main
args, build_args = _parse_args(list(argv))
~~~~~~~~~~~^^^^^^^^^^^^
File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sphinx_autob …
```
=> Don't require the output dir to exist at startup, it might not exist yet

.github/workflows/ci.yml, .github/workflows/create-release.yml
Fix these warnings:
> The following actions use a deprecated Node.js version and will be forced to run on node20: actions/setup-python@v4, actions/cache@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
https://github.com/sphinx-doc/sphinx-autobuild/actions/runs/10678901212
=> Bump GitHub Actions

sphinx_autobuild/build.py
This change makes it so that we don't rely on the correct `sphinx-build` being on PATH to build the docs.
This is useful when the command that runs sphinx-autobuild runs in a virtualenv that isn't the currently activated virtualenv (i.e. via `uv run --extra docs` invocation)
=> Don't rely on PATH to find sphinx-build

sphinx_autobuild/build.py
=> Improve handling for errors in pre-build commands

README.rst, sphinx_autobuild/__main__.py, sphinx_autobuild/build.py, tests/test_application.py
This PR is a rework of #143:
1. Rebase to master
2. Add use case
cc @e-roux, @AA-Turner.
=> Add a `--post-build` argument
